### ISSUE TITLE
Does this support FeatureServer ?

### ISSUE THREAD

**Issue by vr00n** [JasonSanford/shapefile-ags#1]
Just hangs on trying this.. Is it beacuse this is a FeatureServer. Your examples all have MapServer in them.

Thanks
`shapefile-ags https://services1.arcgis.com/XXXXX/arcgis/rest/services/Assessment/FeatureServer/0/query --file-name='LA.zip'
`

**Comment by JasonSanford** [comment]
FeatureServers seem to be working for me. It looks like you've added `/query` to the end of the URL. It might work if you take that out.
